# Site settings
title: Borin9 Blog
SEOTitle: Boring的博客 | Boring Blog
header-img: img/claudio-testa-306745-unsplash.jpg
email: huxpro@gmail.com
description: "关于程序与设计、黑客与画家 | @boring0x00，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @boring0x00 的个人博客，与你一起发现更大的世界。"
keyword: "web pwn c c++ java python"
url: "https://boring0x00.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     boring
zhihu_username:     zhu-bo-41-47
github_username:    boring0x00
twitter_username:   boring0x00
#facebook_username:  boring


highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: boring

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: boring



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/pedro-lastra-143326-unsplash.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
{
    #     title: "Su",
    #     href: "http://su.gallery/"
    # }, 
        title: "xing",
        href: "http://blog.xingssr.cn"
    },{
        title: "rep",
        href: "https://repw.github.io/"
    },{
        title: "threst",
        href: "https://threst.github.io/"
    },{
        title: "nu11hex",
        href: "https://nu11hex.github.io/"
    },{
        title: "f1sh",
        href: "http://f1sh.site/"
    }
]
